### ISSUE TITLE
Javascript errors in console when opening hamburger menu (which also doesn't open)

### ISSUE THREAD

**Issue by integricho** [Outernet-Project/librarian#258]
Possibly during the merge of bundles, either the order or some of the files were left out, these errors appear:

    Name elements.Element already defined with value undefined
    Name elements.ExpandableBox already defined with value undefined
    Name widgets.PulldownMenubar already defined with value undefined
    Name widgets.ContextMenu already defined with value undefined
    Name widgets.Statusbar already defined with value undefined

**Comment by foxbunny** [comment]
Looks like double-inclusion of some lower-level classes.

**Comment by foxbunny** [comment]
Looking at compiled JS, it *is* indeed double-inclusion of assets.

**Comment by integricho** [comment]
No longer an issue, seems to be properly fixed in #268
