### ISSUE TITLE
Setup wizard not started in local environment

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian#261]
After starting Libraian in a prepared development environment, setup wizard is not started. Because of this, the session key is not created, and we get an error:

```
ConfigurationFormatError("Configuration error in section [session]: missing 'secret' setting",)
```

Fixing this issue obsoletes #259.

Temporary workaround is to add `session.secret` key in development configuration as per the fix in #259.

**Comment by integricho** [comment]
Also fixed with the reintegration of the setup module.
