### ISSUE TITLE
Find and add missing assets

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian#267]
The following assets are unaccounted for (bundle name in parens):

- [x] wizard.coffee (in js/wizard) **it's actually CSS**
- [x] setup.coffee (in js/setup) **it's actually CSS**
- [ ] language_step.scss (in css/wizard)
- [ ] $(STATIC_DIR)/css/vendor/dummy.css <-- ?? (in css/wizard)

**Comment by integricho** [comment]
Obsolete.
