### ISSUE TITLE
System information on setup page

### ISSUE THREAD

**Issue by syedkarim** [Outernet-Project/librarian#280]
I would like to see the following information presented on the /setup page. This would greatly speed up the pre-shipping QA process for Lighthouses. 

- firmware version number
- available tuner
- mounted storage points

**Comment by foxbunny** [comment]
Is there any reason it needs to be on the setup page?

**Comment by syedkarim** [comment]
It's the first page that comes up when connecting to the network. It just
streamlines the process. It could easily be another page, of course. I
would just set the default browser start page to whatever url displayed
that information.
ᐧ

**Comment by foxbunny** [comment]
Ok. I think it would be easier to make it a separate page.

**Comment by syedkarim** [comment]
Works for me. Then it's basically the old /diag page, which worked just
fine.
ᐧ

**Comment by foxbunny** [comment]
Basically, but we'll revisit the diags page to make sure it works reliably.

**Comment by integricho** [comment]
Resolved with a set of cgi scripts outside of librarian itself
