### ISSUE TITLE
From FCBH: Settings are not persistent - WiFi SSID, Channel, Country

### ISSUE THREAD

**Issue by syedkarim** [Outernet-Project/librarian#336]
When more than one Lantern is in close proximity, the SSIDs will need to be changed.  No problems changing them.  However, if the Lantern reboots, then the SSID setting reverts back to default (Outernet).  Same thing if the WiFi channel or country is changed - they go back to default after reboot.  This could be an issue when training during fielding when there will be multiple Lanterns in the same room.

**Comment by integricho** [comment]
Using the latest rxOS hotfix release, this issue is not reproducible, settings are persistent across reboots.

**Comment by foxbunny** [comment]
Probably using firmware that does not contain the fix. Closing for now.
