### ISSUE TITLE
Support local installable rxOS overlay collection

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian#341]
This is probably a better target for a separate component, but I'll log it here.

Experimental software like demods may require an easy way to revert to some previous version, or even compare performance between multiple different versions. Since there is no (easy) way to tell whether some version is successful or not without human assistance, an UI must exist that allows selection of different software versions. 

Since rxOS already has overlay support which are quite similar to packages, they may be used as packages and managed by the software version management (SVM) component.

# SVM overview

The software version management (SVM) component will:

- maintain a stash of overlay images in persistent storage
- install (different versions of) overlays into /boot
- remove overlays from the stash
- keep track of the amount of storage used by overlays
- warn users when overlays take up more than a predefined percentage of storage

# Overlay metadata

The overlay files have the following filename format:

    overlay-<name>-<version>.sqfs

The `<name>` is an alphanumeric string with no special characters, underscores, etc. `<version>` is in a `X.Y[.Z][S]` format, where Z is a zero-padded, 3-digit number, and S can be one of the 'aN', 'bN', or 'rcN'.

No other metadata is provided.

# UI

The user interface should be exposed through the settings page. It should list all available overlays by name only, and provide a drop-down.

The drop-down should:

- contain an ordered available versions for each
- contain a 'not installed' option when the overlay is not installed at all
- contain an 'uninstall' option when any version is installed
- have currently installed version selected by default if any

Changing the drop-down value to another version should reveal an 'apply' button, which installs the selected version replacing any installed versions if present.

A 'trash' button should be shown next to each overlay that removes the selected overlay _version_ from the stash, and also uninstalls it if it's installed. When using the trash button on an installed overlay version, the drop-down should show 'not installed' after the operation completes.

After installing or uninstalling an overlay, user should be prompted to reboot the system. In addition a 'reboot' button may be shown which reboots the system.

Total size of all overlays should be shown below the list.

# Installing and removing overlays

Overlays live in the `/boot/` directory, which is a mount point for `ubi0:linux` filesystem. This filesystem is mounted read-only on boot, and must therefore be mounted read-write in order to perform changes on it. Special care may be required to perform this operation only when no OTA updates are happening, because OTA updates typically change the same moutpoint.

When replacing existing overlays, recommended procedure is to write the new overlay to a path that is different from the target path (e.g., by adding a `.new` extension to the intended path), then move the existing overlay to a path that has a `.backup` extension, and finally move the `.new` file to the target path:

    cp /stash/overlay-foo.sqfs /boot/overlay-foo.sqfs.new
    mv /boot/overlay-foo.sqfs /boot/overlay-foo.sqfs.backup
    mv /boot/overlay-foo.sqfs.new /boot/overlay-foo.sqfs

# TBD

- How do overlays get added to the stash?
- How do we differentiate between overlays that should be managed and those that should not?

**Comment by abgoyal** [comment]
1. overlay may need a descriptive name to be used in the enduser UI. This name may be provided externally from the overlay image itself - for example in a file also provided by the same ota package that delivered the overlay version

2. In overlay-name-ver.sqfs, the UI will ensure that exactly one of each overlay-name-*.sqfs is installed.

**Comment by foxbunny** [comment]
> overlay may need a descriptive name to be used in the enduser UI. This name may be provided externally from the overlay image itself - for example in a file also provided by the same ota package that delivered the overlay version

When using 'descriptive' names, i18n support may become a problem.

> In overlay-name-ver.sqfs, the UI will ensure that exactly one of each overlay-name-*.sqfs is installed.

SVM will always replace overlays of the same name when installing, so this should not be a problem.
