### ISSUE TITLE
Removal of Updates and Browser tabs in FCBH overlay

### ISSUE THREAD

**Issue by syedkarim** [Outernet-Project/librarian#349]
For this particular overlay, the customer has requested that only the index page be presented to the end user. Displaying content in the Updates and Browse tabs creates confusion.

**Comment by integricho** [comment]
Does this mean that they don't intend to use the librarian UI at all for accessing the content? That is, not even in the future? If we disable those tabs, even if only in their overlay, that basically cuts down on the general usefulness of librarian as a whole, and just to repeat once again, they won't be able to traverse the content at all through the UI with it.

**Comment by syedkarim** [comment]
I'll find out for sure.

**Comment by syedkarim** [comment]
During the meeting they expressed an interest in controlling the content experience through the customized landing page/index page. I am waiting on confirmation of their intent.

**Comment by integricho** [comment]
Resolved with Outernet-Project/librarian-simplified
