### ISSUE TITLE
Notification at bottom of screen can not be deleted

### ISSUE THREAD

**Issue by syedkarim** [Outernet-Project/librarian#354]
When I click on the message bar at the bottom of the screen, I am unable to delete the message. 

![image](https://cloud.githubusercontent.com/assets/1186964/17640930/c54622ee-60d1-11e6-9220-88ebf9ffa11a.png)

**Comment by foxbunny** [comment]
Some messages are permanent and cannot be removed.

**Comment by foxbunny** [comment]
That is, these messages are automatically removed when the condition they refer to no longer applies.

**Comment by integricho** [comment]
Fixed in 62006b9fc675281a91c5408cbbfff532ebfe705f (for non-permanent notifications), and the disk-space limit issue has been addressed in Outernet-Project/rxOS@6241c19bc0d16633c51f07267662f6d627837122
