### ISSUE TITLE
Network signal strength indicator on top right does not update without page reload

### ISSUE THREAD

**Issue by abgoyal** [Outernet-Project/librarian#357]

**Comment by foxbunny** [comment]
More information needed:

- browser
- OS
- image version
- whether there is anything out of place in the Network tab in the browser's developer tools (if dev tools exist)

**Comment by abgoyal** [comment]
Image: 0815
Browser: Chrome Version 52.0.2743.82 (64-bit)
OS: Linux Mint 14 x64

**Comment by foxbunny** [comment]
Any errors in the dev tools?

**Comment by abgoyal** [comment]
Not that I can see. status queries seem to be coming in regularly.

**Comment by foxbunny** [comment]
Not able to reproduce in any of the browsers. Can someone else jump with a quick test? @syedkarim @integricho @zodoczi

**Comment by foxbunny** [comment]
It's also possible that this only happens for certain parameters? I don't have a radio yet, so can't test all states.

**Comment by abgoyal** [comment]
I can't replicate this anymore. On CHIP or RPI3. Consider it closed for now. If I replicate, we can reopen.
