### ISSUE TITLE
Frequency change in web gui doesn't take effect, only after reboot

### ISSUE THREAD

**Issue by zodoczi** [Outernet-Project/librarian#358]
[diags_rxos_2016-08-17_11-39-51.log.txt](https://github.com/Outernet-Project/librarian/files/422477/diags_rxos_2016-08-17_11-39-51.log.txt)

**Comment by zodoczi** [comment]
![pasted image at 2016_08_17 12_33 pm](https://cloud.githubusercontent.com/assets/16337823/17735066/a4d4c3d2-6480-11e6-9c2c-0be48edd54ee.png)

**Comment by foxbunny** [comment]
@zodoczi Can you verify in the demo UI whether the change takes effect even though the Librarian interface does not update?

**Comment by zodoczi** [comment]
I confirm it does not take effect as paralel monitoring CHIP from SSH and "SDR" debug window was running, no lock. Now tried it again, still not updating tuner's settings.
