### ISSUE TITLE
Web gui debug info wish and typo

### ISSUE THREAD

**Issue by zodoczi** [Outernet-Project/librarian#359]
Selected frequency is MHz not Mhz
![image](https://cloud.githubusercontent.com/assets/16337823/17735303/aea4befc-6481-11e6-88f6-17f984828400.png)

Also please include the "AFE Gain" parameter too in Tuner settings page, this will be important for upcoming evaluations as now SDR gain is massively overloaded.

Thanks!

**Comment by foxbunny** [comment]
> Also please include the "AFE Gain" parameter too

I don't think the demod makes that available to us via the socket. I'll let @integricho look into it, tho.

**Comment by zodoczi** [comment]
Thanks!

2016. aug. 19. du. 1:12 ezt írta ("Hajime Yamasaki Vukelic" <
notifications@github.com>):
