### ISSUE TITLE
RF parameters logging feature for monitoring quality of service

### ISSUE THREAD

**Issue by zodoczi** [Outernet-Project/librarian#360]
We had discussion about this in the past and it's still actual. I imagine something like a simple data logging feature offline and possibly later online (uploaded to a server) in case of our remotes. 

Now the web gui "Tuner settings" surface gives a really good feedback of the actual state of the receiver system, I really like it! 

However for long term reliability tests and statistical overview of a few days reception period, it's can't be used. Aggregated data possibly can visualized on server side / PC browser side, CHIP might only contain and upload logged telemetry (like SNR, RSSI, offset freq, etc.)
For example: https://www.yourkit.com/docs/java/help/perf_charts.jsp
![image](https://cloud.githubusercontent.com/assets/16337823/17739923/0a00db18-6497-11e6-8388-150a43f9eb9f.png)

Thanks

**Comment by syedkarim** [comment]
This is exactly what Abhishek is working on now ;)
ᐧ

**Comment by zodoczi** [comment]
Excellent! This will be really important for us in the near future.

**Comment by foxbunny** [comment]
Wrong repo. Closing.
