### ISSUE TITLE
Click on "Mark as read" never removes error message in web gui

### ISSUE THREAD

**Issue by zodoczi** [Outernet-Project/librarian#362]
New notification message keep going. Mark as read works only till a reboot.

![image](https://cloud.githubusercontent.com/assets/16337823/17748178/7428511c-64b8-11e6-891b-5c475d588b58.png)

Version: "Librarian v4.0.post2 / rxos 2.0a1"

**Comment by integricho** [comment]
Fixed in 62006b9fc675281a91c5408cbbfff532ebfe705f
