### ISSUE TITLE
"storage space is getting too low" false notification 

### ISSUE THREAD

**Issue by zodoczi** [Outernet-Project/librarian#366]
Even if having 1.4 GB free space, CHIP pendriveless remote mode

**Comment by zodoczi** [comment]
![screenshot_2016-08-28-17-36-01-378_com android chrome](https://cloud.githubusercontent.com/assets/16337823/18034823/f406ce22-6d46-11e6-83ad-ec7e1f0ca50e.png)
![screenshot_2016-08-28-17-36-09-072_com android chrome](https://cloud.githubusercontent.com/assets/16337823/18034828/01f9a2ac-6d47-11e6-81c4-dbc622c6932e.png)

**Comment by syedkarim** [comment]
This needs to be resolved in the next build. A user on the forums also pointed this out. The notification should not display until there is less than 600MB of space available.

**Comment by integricho** [comment]
Fixed in Outernet-Project/rxOS@6241c19bc0d16633c51f07267662f6d627837122
