### ISSUE TITLE
[NEW COMPONENT] Remote support configuration

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian#370]
Since rxOS REMOTE file mechanism is scheduled for removal, a new Librarian component is required to take over the role of remote support set-up. The new component should, specifically, handle the KEY, PORT, and HOSTNAME keys from the REMOTE file.

Settings should be persisted using the Librarian's standard settings mechanism (librarian.json), and a command line tool should be provided as part of the component that allows shell scripts to obtain the appropriate information.

Separately, a patch should be made for the rxOS remote-support local package to make use of the saved settings settings.

**Comment by abgoyal** [comment]
How would this be configured by the user?

**Comment by integricho** [comment]
This has been implemented in Outernet-Project/librarian-remote
