### ISSUE TITLE
Please add "up time counter" to tuner settings page

### ISSUE THREAD

**Issue by zodoczi** [Outernet-Project/librarian#403]
This new (and easy) telemetry data would be really useful for evaluation. Simply measuring up time spent since boot up.

Also possibly the log can use a time stamp from 0 sec, counting up after successful boot.

**Comment by abgoyal** [comment]
you can check uptime over ssh with the "uptime" command. As librarian is frozen, no new elements are being added to it.

**Comment by zodoczi** [comment]
wow, great! :) good for me, thanks!
